log:
  exp_name: bunny_step3
guide:
  text: "a photo of a bunny, {} view"
  diffusion_name: stabilityai/stable-diffusion-2-depth
  shape_scale: 0.6
  append_direction: True
  shape_path: shapes/bunny.obj
  reference_texture: textures/tex_localpatch.png
  initial_texture: textures/tex_scribble_localpatch.png
optim:
  seed: 2
